"""initial

Revision ID: e238977d1028
Revises: 
Create Date: 2026-04-21 23:29:53.677373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e238977d1028'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_schedule_id'), 'resource_schedule', ['id'], unique=False)
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.create_index('uq_active_username', 'user', ['username'], unique=True, postgresql_where='is_active = true')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_username', table_name='user', postgresql_where='is_active = true')
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_resource_schedule_id'), table_name='resource_schedule')
    op.drop_table('resource_schedule')
    # ### end Alembic commands ###
